image: node:8

stages:
  - test

before_script:
  - sudo apt install raptor2-utils mongodb-server
  - npm install
  - make bootstrap-test

test:
  stage: test
  script:
    - make test-all
  cache:
    paths:
    - node_modules/
