%YAML 1.1
# -*- coding: UTF-8, tab-width: 4 -*-
---

language: node_js

node_js:
  - "12"

sudo: false

dist: focal

addons:
  apt:
    packages:
    - raptor2-utils

install:
  - ./install.sh

script:
  - npm test
  - make bootstrap-test
  - make test-all







...
