%YAML 1.1
# ^-- ATTN: [2019-12-31] If you use a later version, Github will fail
#     with a bogus error message "You have an error in your yaml syntax".
# -*- coding: UTF-8, tab-width: 4 -*-
---

on:
    push:
        branches:
            -   '*'

jobs:
    job_ci_test:
        runs-on: ubuntu-latest
        name: 'CI tests'
        steps:
            - run: 'git config --global init.defaultBranch master'
            - run: 'sudo apt-get install raptor2-utils'

            - uses: actions/setup-node@v2
              with:
                node-version: 12

            - run: 'npm install --global npm@7'

            - uses: actions/checkout@v2

            - run: './install.sh'

            - name: 'Start MongoDB'
              uses: supercharge/mongodb-github-action@1.6.0
              with:
                mongodb-version: 3.6

            - run: 'make bootstrap-test'
            - run: 'make test-all'

...
